In [84]:
import numpy as np

X = np.array([[1,2],[3,4],[4,5]])
theta = np.array([5, 6])
y = np.array([1, 2, 1])

def logistic_func(theta: np.ndarray, x: np.ndarray) -> float:    
    sigmoid = lambda x: 1/(1+np.exp(-x))
    return sigmoid(x @ theta)

def logistic_func_all(theta: np.ndarray, X: np.ndarray) -> np.ndarray:
    return logistic_func(theta=theta, x=X)
    
def cross_entropy_loss(theta: np.ndarray, X: np.ndarray, y: np.ndarray) -> float:
    return np.log(1 + np.exp(-y * (X @ theta)), dtype=float).mean()
    
def grad_cross_entropy_loss(theta: np.ndarray, X: np.ndarray, y: np.ndarray) -> np.ndarray:
    sigmoid = lambda x: 1/(1+np.exp(-x))
    return (-y * X.T * sigmoid(-y * (X @ theta))).T.mean(axis=0)

In [85]:
cross_entropy_loss(theta, X, y)

1.3799792134237091e-08

In [86]:
grad_cross_entropy_loss(theta, X, y)

array([-1.42953957e-23, -1.22910189e-38])

In [87]:
sigmoid = lambda x: 1/(1+np.exp(-x))

In [117]:
(y * X.T * sigmoid(-y * (X @ theta)))

array([[4.13993755e-08, 8.00168889e-34, 7.71499939e-22],
       [8.27987509e-08, 1.06689185e-33, 9.64374924e-22]])

In [126]:
(-y * X.T * sigmoid(-y * (X @ theta))).T.mean(axis=0)

array([-1.37997918e-08, -2.75995836e-08])