In [73]:
import numpy as np

X = np.array([[1,2],[3,4],[4,5]])
theta = np.array([5, 6])
y = np.array([1, 2, 1])

In [123]:
def linear_func(theta, x):
    shape = len(x.shape)
    if shape == 1:
        return (x*theta).sum(axis=0)
    else:
        return (x*theta).sum(axis=1)

def linear_func_all(theta, X):
    return linear_func(theta, X)

def mean_squared_error(theta, X, y):
    M = len(X)
    return 1/M * ((y - linear_func_all(theta, X))**2).sum()

def grad_mean_squared_error(theta, X, y):
    h = linear_func_all(theta, X)
    M = len(X)
    const = 2/M * (y - h)
    X_trans = -X.transpose()
    return (const * X_trans).sum(axis=1)

In [124]:
linear_func(theta, X)

array([17, 39, 50])

In [125]:
linear_func_all(theta, X)

array([17, 39, 50])

In [126]:
mean_squared_error(theta, X, y)

1342.0

In [127]:
grad_mean_squared_error(theta, X, y)

array([215.33333333, 283.33333333])